### ISSUE TITLE
Updating to 0.96.2.5 all town and nation balances change to -2750

### ISSUE THREAD

**Issue by cobrex1** [TownyAdvanced/Towny#4192] opened 2020-07-19 20:53 UTC
### What steps will reproduce the problem?
1. Using Iconomy and Towny 0.96.2.4 and flatfile storage
2.Update to Tonwy 0.96.2.5
3.

### What is the expected output?
1. Nothing should change regarding towns and nations, but all town and nation balances changed to -2750. There were no errors in the logs. The only refernce to this number is the default balnce in the Iconomy yml, but cannot see that being the issue.

But I am getting this now as players log in:
[10:26:27] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 496997.0
This looks like the player's balance but I think only happens on first login from update to 0.96.2.5

### What is your Towny version?
0.96.2.5

### What is your spigot/craftbukkit version?
Paper 1.15.2 #379

1. Your full server startup from the logs\latest.log :
https://hastebin.com/ayonuyegol.md

2. Your Towny config.yml (if using MySQL please remove password,) :
https://hastebin.com/ajacuceyay.coffeescript

**Comment by cobrex1** [comment] 2020-07-19 20:58
I am also getting these errors in console:

[15:48:44] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 394215.56
[15:48:44] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 1250.0
[15:48:44] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 1250.0
[15:48:44] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] Your town lost 2.50 Dollars.
[15:48:44] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 1250.0
[15:48:44] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 1250.0
[15:48:44] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] [Nation Msg] Empire: Your nation lost 2.50 Dollars.
[15:48:44] [Server thread/INFO]: benadryl became entangled in Lvl 75 Elite Spider's web!
[15:48:51] [Server thread/INFO]: benadryluver issued server command: /home ent
[15:48:59] [Async Chat Thread - #2/INFO]: [CHAT] DJP130: ouchie
[15:49:28] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 394210.56
[15:49:28] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 1247.5
[15:49:28] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 1247.5
[15:49:28] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] Your town lost 2.50 Dollars.
[15:49:28] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 1247.5
[15:49:28] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 1247.5
[15:49:28] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] [Nation Msg] Empire: Your nation lost 2.50 Dollars.

**Comment by Yldales** [comment] 2020-07-19 21:07
The `[Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: ...` errors also occurs on a fresh Towny installation (Paper-1.16.1-101, Towny 0.96.2.5 and Vault 1.7.2-b107), when a player join. The numbers displayed seems to match the player's town balance.

**Comment by cobrex1** [comment] 2020-07-19 21:26
I am also getting this error too with /tc chat channel - sorry Llmdl :(

[16:24:47] [Async Chat Thread - #9/ERROR]: Could not pass event AsyncPlayerChatEvent to TownyChat v0.73
java.lang.NoSuchMethodError: com.palmergames.bukkit.towny.TownyAPI.getOnlinePlayers(Lcom/palmergames/bukkit/towny/object/Town;)Ljava/util/List;
	at com.palmergames.bukkit.TownyChat.channels.StandardChannel.chatProcess(StandardChannel.java:81) ~[?:?]
	at com.palmergames.bukkit.TownyChat.listener.TownyChatPlayerListener.onPlayerChat(TownyChatPlayerListener.java:160) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1117.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-379]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1782) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1697) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-379]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[16:24:47] [Async Chat Thread - #9/INFO]: ♂ [Guild]<Cobrex_> hi

Not sure where 'guild' is coming from?

**Comment by suneettipirneni** [comment] 2020-07-19 23:13
So I've properly identified what the issue is for the balances, the default economy balance is indeed the issue, however, it is an issue on our side, not yours, and will be fixed asap. For now, there's a temporary solution that will work.

1.) Stop Server
2.) Change default eco account money to 0 for new accounts
3.) Edit the `debt_prefix` config option and change it to `[debt]-` basically from uppercase to lowercase.
4.) Start the server and let it load.
5.) Put back the default eco account balances
6.) Restart again.

As for the chat error spam, I have also identified that error and will be sending a jar that should work.

**Comment by suneettipirneni** [comment] 2020-07-19 23:31
This TownyChat jar should fix the error spam
[TownyChat-0.73.jar.zip](https://github.com/TownyAdvanced/Towny/files/4944848/TownyChat-0.73.jar.zip)

**Comment by suneettipirneni** [comment] 2020-07-19 23:37
Ignore the last comment, the patched TownyChat jar is available here:

https://github.com/TownyAdvanced/TownyChat/releases/tag/0.74

**Comment by cobrex1** [comment] 2020-07-20 05:22
Thanks for the updatedr Chat jar, that has fixed the error, however, regarding the balances, the above steps were followed, and on the second restart, town balances were untouched and appear ok, however, Nation balances all reset to -2750. 

I then used /ta nation [nation] deposit [amount] for the nations on the server and these are the errors from console, however, all nations now have a positive balance as before the above steps were taken:

[00:13:45] [Server thread/INFO]: king_cobrex issued server command: /ta nation Anicetus deposit 8000
[00:13:45] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 2750.0
[00:13:45] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] [Nation Msg] Anicetus: king_cobrex deposited 8000 into the Nation bank.
[00:13:57] [Server thread/INFO]: king_cobrex issued server command: /ta nation Empire deposit 8000
[00:13:57] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 2750.0
[00:13:57] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] [Nation Msg] Empire: king_cobrex deposited 8000 into the Nation bank.
[00:14:09] [Server thread/INFO]: king_cobrex issued server command: /ta nation Republic deposit 8000
[00:14:09] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 2750.0
[00:14:09] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] [Nation Msg] Republic: king_cobrex deposited 8000 into the Nation bank.
[00:14:20] [Server thread/INFO]: king_cobrex issued server command: /ta nation TheUpperWeast deposit 8000
[00:14:20] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 2750.0
[00:14:20] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] [Nation Msg] TheUpperWeast: king_cobrex deposited 8000 into the Nation bank.
[00:14:32] [Server thread/INFO]: king_cobrex issued server command: /ta nation Weebs deposit 8000
[00:14:32] [Server thread/WARN]: [com.palmergames.bukkit.towny.Towny] [Towny] Error: 2750.0
[00:14:32] [Server thread/INFO]: [com.palmergames.bukkit.towny.Towny] [Nation Msg] Weebs: king_cobrex deposited 8000 into the Nation bank.

**Closed** 2020-07-20 19:00 UTC
Labels: bug
