### ISSUE TITLE
"Async task for Towny v0.101.0.0 generated an exception"

### ISSUE THREAD

**Issue by leothawne** [TownyAdvanced/Towny#7689] opened 2024-12-01 04:05 UTC
### What steps will reproduce the problem?

1. Updated from Towny 0.100.4.0 to 0.101.0.0

### What is the expected output?

Stop spamming my server console

### Towny version

0.101.0.0

### Server version

git-Purpur-2176 (MC: 1.20.4)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: 
[latest.log](https://github.com/user-attachments/files/17967785/latest.log)

2. Your Towny config.yml: 
[config.yml.txt](https://github.com/user-attachments/files/17967786/config.yml.txt)

3. Your townyperms.yml: 
[townyperms.yml.txt](https://github.com/user-attachments/files/17967787/townyperms.yml.txt)

4. Your log's error: 
![image](https://github.com/user-attachments/assets/61a36445-ba5f-424c-9786-4735be07e182)

(optional) If this is to do with permissions,
5. Your permissions file:

(optional) If this is to do with chat,
6. Your chatconfig.yml:
7. Your channels.yml:

**Comment by leothawne** [comment] 2024-12-01 04:14
Latest.log: [https://pastebin.com/HnppQtu0](https://pastebin.com/HnppQtu0)
Config.yml: [https://pastebin.com/97MwQX7x](https://pastebin.com/97MwQX7x)
Townyperms.yml: [https://pastebin.com/LAVKDV5M](https://pastebin.com/LAVKDV5M)

**Comment by Warriorrrr** [comment] 2024-12-01 10:29
Duplicate of #7687, this is already fixed in the latest pre-release

**Closed by Warriorrrr** 2024-12-01 10:29 UTC
Labels: bug
