### ISSUE TITLE
Nation changes are not being saved to the TOWNY_NATIONS table.

### ISSUE THREAD

**Issue by Momshroom** [TownyAdvanced/Towny#2989] opened 2018-07-20 17:37 UTC
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. set a nation spawn with /n set spawn or join or leave a nation, move the captital, etc. (I tested setting a nation spawn, having a town leave a nation, having a town join a nation, moving the capital of a nation to another town that was already in that nation, changing alliances-- none is remembered after reload because none is changed in the mysql) (I ALSO tested adding money to the nation bank- that is remembered.  I tested making someone nation assistant... interesting towny remembers they are nation assistant in game (tested across /ta reload but not yet across a server restart) http://prntscr.com/k8ylww, but the nation mysql table does not change to reflect that they are.  It may be getting it from the player's resident file?)  All other tables seem to operate as expected.  A resident joining or leaving a town, for example IS recorded and does stay across reloads)
2. use /n spawn, or look at /n.  The changes you made were actually made.  It works in game but nothing is changed in the mysql table.
3. /ta reload OR restart server.. Every nation change you just made is forgotten.  If you check the mysql towny_nations table, nothing has been changed in it from before you started.
4. you can repeat this and reset the nation spawn or change nations back after /ta reload, but towny begins throwing errors.  Worldedit begins throwing LOTS of errors as blockshub can no longer get permissions from towny.

### What is the expected output?
1. Nation data changes will get saved to the TOWNY_NATIONS table.
2. Towny reload after nation changes will not cause them to be forgotten or for towny to begin throwing NPEs
3. That towny reloads and nation changes will not effect the behavior of worldedit.

### What is your Towny version?
Do not say "latest".
0.92.0.12

### What is your spigot/craftbukkit version?
Do not say "latest".
CraftBukkit version git-Spigot-eb3d921-b9f1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/YANjwWZv
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/EWP0vCZE
3. Your townyperms.yml : https://pastebin.com/h3Xq1r94
4. Your log's error :  https://pastebin.com/FhUm9186 (this is three separate errors pasted into one file.  At least the first two errors repeat frequently. I haven't saved a copy of the errors from when someone tries to worldedit after a /ta reload because no one was trying this cycle.  If you need them, please let me know.)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment] 2018-07-22 16:08
Tested this today, could not reproduce.
Steps:
- Create a town, create a nation
- Claim a plot next to town spawn, set nation spawn in said plot.
- Toggle nation's public status.
- /ta reload, /reload, stop and start server, all three did not wipe nation data.

**Comment by LlmDl** [comment] 2018-07-22 16:09
Could there be something about that table on your mysql server which has had it's permissions changed which would prevent towny from writing to it?

**Comment by Momshroom** [comment] 2018-07-22 16:34
It shouldn't have.   We had no issues before I updated towny and the rest of towny changes get saved.  It's all the same database, just different tables.  The issue also occurs on both our test and public servers, which have completely separate MySql.  I can try wiping the towny tables on my test server and reverting towny to my old version there and make sure the problem doesn't exist.   (I can't revert with the data I have as towny really doesn't like it.)

**Comment by Momshroom** [comment] 2018-07-22 16:47
I deleted the towny_nations table on my test server and restarted.  Now when I make a new nation, the data is saved and loaded properly.  I was updating from towny version 0.91.4.13.  Is it possible the tables were different enough that towny is having trouble with them?

**Comment by Momshroom** [comment] 2018-07-22 17:45
The data tables are no longer in the same order.  On my test server with a brand new nation table, the tables goes:
taxes, spawncost, neutral, uuid, registered
On the older production server table, it goes:
taxes, neutral, uuid, spawncost, registered.
However, moving the collumns on the new table to their positions on the old one doesn't break it.

Also, I am now able to save my nation board and spawn point on the production server, but I start getting console errors from towny right after reloading. http://prntscr.com/k9kt1l

My old table on the production server has NULL values for "registered" and "nation board" on almost all nations (the exception being my nation I just set a nation board on, which, come to think of it is the nation I'm testing to see if it saves information and now is saving it... )  YES!  Found it... If I set the spawn (or other info) of a nation without a town board (so it has null settings in the table), it is not saved on reload. If I set a board message for that nation, data for that nation is now saved.  
So the problem is my NULL entries in my data table.  If it's not just me, perhaps towny needs to write those values into new tables.

**Comment by LlmDl** [comment] 2018-07-22 18:11
I believe I've spotted it. We're calling for the nationSpawn to never be null but it's not like a townSpawn which is always set at some point.

Try doing an update from the old tables to this build:
https://www.dropbox.com/s/tkv488r6lw7biwp/Towny.jar?dl=0

**Comment by Momshroom** [comment] 2018-07-22 18:38
https://pastebin.com/p5rAEV6R

That's the error when I load that version on my test server which had a new towny_nations table already.

**Comment by LlmDl** [comment] 2018-07-22 18:40
That's a wholly separate thing, where town blocks are missing a town but are still saved in the database. AFAIK we auto-purge those in flatfile and maybe in mysql now too. 

Can you tell me if you have any issues using that build to update a server that still has the old nation tables which are missing nationSpawns, isPublic, nationBoard?

**Comment by Momshroom** [comment] 2018-07-23 04:10
Java 8

**Comment by Momshroom** [comment] 2018-07-23 14:31
It really doesn't seem to care if I have a nation spawn set or not... just the board.  The new file fills that in with directions on how to set one, but the updated file doesn't.

**Comment by LlmDl** [comment] 2018-08-29 13:06
If you still have an issue with the boards, I have another build here for you to test with:
https://www.dropbox.com/s/e9hi2ykym8430l3/Towny-momshroom.jar?dl=0

**Comment by LlmDl** [comment] 2018-09-02 15:43
Reported as fixed by Momshroom

**Closed by LlmDl** 2018-09-02 15:43 UTC
Labels: Completed, Label-Data, bug
