### ISSUE TITLE
Suggestion: an alliance

### ISSUE THREAD

**Issue by Oleksiy13321** [TownyAdvanced/Towny#5813] opened 2022-03-18 13:56 UTC
### **Please explain your feature request to the best of your abilities:**

I would like to be able to create an alliance for which to add a name and invite nations to it, such as in the game hearts of iron 4. what would alliances do? well for example to fight together with plugin eventwar, to teleport to the allied cities, to deposit each other in the city or the nation.

**Comment by ItsJuls** [comment] 2022-03-21 05:40
yes i would also like this thing

**Comment by LlmDl** [comment] 2022-04-28 12:42
Duplicate of #5881

**Closed by LlmDl** 2022-04-28 12:42 UTC
Labels: enhancement
