### ISSUE TITLE
Suggestion: Outpost marker for Dynmap

### ISSUE THREAD

**Issue by LeftTheNegotiator** [TownyAdvanced/Towny#5123] opened 2021-07-27 18:54 UTC
**Please explain your feature request to the best of your abilities:**
Hello,

I would like to request a custom marker in Dynmap-towny for outposts. I see some servers use custom plugins for them, so I was wondering if they were ever planned to be added as a main feature.

**Comment by LlmDl** [comment] 2021-07-27 19:24
Duplicate of #3591

**Closed by LlmDl** 2021-07-27 19:24 UTC
Labels: Label-Dynmap, enhancement
