### ISSUE TITLE
Regenerating unclaimed makes ores

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [TownyAdvanced/Towny#2855] opened 2018-02-21 22:04 UTC
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Claim new area
2. Get all ores
3. Unclaim
4. Ores are regenerating, although they are in the ignore list

### What is the expected output?
1. Ores not regenerating

### What is your Towny version?
Do not say "latest".
0.92.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
PaperSpigot 1.12 Build 1169

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/JERN7Mv0
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/hayGnRBy
3. Your townyperms.yml : https://pastebin.com/gdW0PK0m
4. Your log's error : none

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

8. World info: https://pastebin.com/1q5pKxyZ

**Comment by LlmDl** [comment] 2018-02-21 23:49
I've tested this on flatfile and mysql servers. No ores were regenerated on either server. 

It wouldn't make a lot of sense but maybe there's another plugin causing this?

**Comment by LlmDl** [comment] 2018-03-16 17:24
Closing because I could not reproduce this issue.

**Closed by LlmDl** 2018-03-16 17:24 UTC
