### ISSUE TITLE
Suggestion: Town Block Merging

### ISSUE THREAD

**Issue by MrLogano** [TownyAdvanced/Towny#3484] opened 2019-11-02 11:33 UTC
Plot Merging:

One feature I think would be beneficial to Towny would be the inclusion of plot merging. This would be a feature used by mayors to group town blocks together under a single name. This would perhaps have a command such as follows;

/plot merge [groupname]
/plot unmerge [groupname]

This grouping would allow residents to claim larger, or abnormally shaped "plots" with much greater ease.

Using /plot claim in a grouped townblock should also claim those individual town blocks. Although the size of grouped plots could perhaps be limited by way of the towny settings.

In my own server, larger plots require myself, or residents to individually claim all of the town blocks that make up the plot. I find that either residents won't claim the whole plot, or will accidentally overlap into another designated plot. This is especially the case for players unfamiliar with towny, but also helpful to servers / mayors who wish to provide larger "plots" than the standard 16x16 town block.

**Comment by LlmDl** [comment] 2019-11-02 12:12
Duplicate of https://github.com/TownyAdvanced/Towny/issues/472

It might end up that the new MetaData stuff being done by Siris can be used, otherwise we'll end up doing a new list for each town of their grouped plots.

**Closed by LlmDl** 2019-11-02 12:12 UTC
Labels: enhancement
