### ISSUE TITLE
Claim filling.

### ISSUE THREAD

**Issue by Vodq** [TownyAdvanced/Towny#6855] opened 2023-07-16 17:22 UTC
# Claimfill

basically, /towny claim fill, that fills your claim after you make borders instead of having to claim everything inside

**Comment by Warriorrrr** [comment] 2023-07-16 17:27
Duplicate of #6624, this isn't a very high priority for us since /res toggle townclaim exists.

**Closed by Warriorrrr** 2023-07-16 17:27 UTC
Labels: duplicate, enhancement

**Comment by Vodq** [comment] 2023-07-17 04:23
shouldn't it be useful since most people want to claim big pieces of land, even the lands plugin has this.
