### ISSUE TITLE
1.14: Change Default Item_Use_Id list from BONEMEAL to BONE_MEAL

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/Towny#3298] opened 2019-06-20 02:31 UTC
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Go to a claimed area that you shouldn't have access to
2. Place bonemeal on the grass

### What is the expected output?
1. Bonemeal should be blocked and should not interact with protected land

### What is your Towny version?
0.93.1.0 Pre Release 2

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper-95

**Comment by LlmDl** [comment] 2019-06-20 14:18
At least pastebin.com the startup and config...

**Comment by Momshroom** [comment] 2019-06-22 14:09
I can confirm having this same issue and it was brought to my attention by Treeo, who also has it and asked me to verify if I did.  I hadn't done the necessary back work to make a ticket of my own.   I'll do that now and add to this ticket.

**Comment by Momshroom** [comment] 2019-06-22 15:14
Config.yml: https://pastebin.com/skUeREUZ
Townyperms.yml: https://pastebin.com/12ZCBACp
I'm also using 0.93.1.0 Pre 2
I'm using Paper 632 (1.13.2)
Startup log: https://pastebin.com/kxYKEa0a

**Comment by LlmDl** [comment] 2019-06-22 18:20
Looks like it's called BONE_MEAL now, try that in the item_use_id list

**Comment by Momshroom** [comment] 2019-06-22 21:36
That fixed it.  Tyvm

**Comment by LlmDl** [comment] 2019-07-06 14:31
Fixed as of https://github.com/TownyAdvanced/Towny/commit/06be203d8808a222d001e9e49aeb995be0599cdd

**Closed by LlmDl** 2019-07-06 14:31 UTC
Labels: bug
