### ISSUE TITLE
Outposts randomly unclaim themselves

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/Towny#3821] opened 2020-03-25 19:05 UTC
### What steps will reproduce the problem?
Not sure...
Outposts randomly unclaim themselves and sometimes unclaim themselves multiple times after reclaiming the unclaimed outposts. (This has happened up to 3 times for some people)

### What is the expected output?
Outposts to not unclaim randomly.

### What is your Towny version?
0.95.2.23

### What is your spigot/craftbukkit version?
Paper 214 (1.14.4)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/GyAVB4Xa
2. Your Towny config.yml : https://pastebin.com/ydeVKcMg
3. Your townyperms.yml : https://pastebin.com/bcqv0d0t
4. Your log's error : N/A

**Comment by LlmDl** [comment] 2020-04-02 20:29
The [pre-release version 0.96.1.1](https://github.com/TownyAdvanced/Towny/releases/tag/0.96.1.1) has what I believe to be a solution to the issue of vanishing TownBlocks described in your ticket. I would appreciate it if you would consider updating to 0.96.1.1 and letting me know if you have any more vanishing TownBlocks.

**Comment by LlmDl** [comment] 2020-04-04 15:01
I am marking this ticket as a duplicate of [the earliest ticket](https://github.com/TownyAdvanced/Towny/issues/3783) filed for this problem, as no one has said they are still experiencing the issue since 0.96.1.1 was put out.

**Closed by LlmDl** 2020-04-04 15:01 UTC
Labels: bug, duplicate
