### ISSUE TITLE
dynmaps-towny throwing exception 97 in console - Still works

### ISSUE THREAD

**Issue by Rand404** [TownyAdvanced/Towny#4021] opened 2020-05-23 00:57 UTC
### What steps will reproduce the problem?
1. Install dynmap + advancedtowny
2. Install dynmap-towny
3. Error should throw after the server is started
4. The plugin still works, error just shows in console

### What is the expected output?
1. Not throwing the exception
2.
3.

### What is your Towny version?
0.95.1.0

### What is your spigot/craftbukkit version?
Paper(298) 1.15.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Latest.log: https://pastebin.com/y7hz0Jet
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/bWFm7GPR
3. Your townyperms.yml : https://pastebin.com/VqFAzvxW
4. Your log's error : https://pastebin.com/aATSkV9W

(optional) If this is to do with permissions, 
5. Your permissions file : -

(optional) If this is to do with chat,
6. Your chatconfig.yml : -
7. Your channels.yml : -

**Comment by suneettipirneni** [comment] 2020-05-23 00:57
Try downloading the latest towny prerelease it should fix this issue.

**Comment by LlmDl** [comment] 2020-05-23 03:01
duplicate of https://github.com/TownyAdvanced/Towny/issues/4007

**Closed by LlmDl** 2020-05-23 03:01 UTC
Labels: bug
