### ISSUE TITLE
Suggestion: Add /t bantown

### ISSUE THREAD

**Issue by davidcanas** [TownyAdvanced/Towny#6638] opened 2023-04-25 17:47 UTC
### **Please explain your feature request to the best of your abilities:**

/t bantown would ban all members belonging to a specific city

example:
/t bantown Florida

all florida members would be banned from the city

**Comment by davidcanas** [comment] 2023-04-25 20:19
add all the city members to the outlaw list

**Comment by davidcanas** [comment] 2023-04-25 20:20
like /t trustcity

**Comment by LlmDl** [comment] 2023-06-05 20:51
Duplicate of #6544

**Closed by LlmDl** 2023-06-05 20:51 UTC
Labels: enhancement, Priority-Low
