### ISSUE TITLE
Regular users can send messages to admin chat but can't see messages sent to it. (Same thing with staff chat)

### ISSUE THREAD

**Issue by MrWardy** [TownyAdvanced/Towny#3176] opened 2019-02-06 03:50 UTC
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Log into the server with a user without any permissions
2. Type /ac (The command to toggle admin chat)
3. Type in chat
4. If possible have an alternate account online with access to admin chat
5. Tab to the alternate account, the user without any permission's message should show up, however it shouldn't show up on the senders screen.

### What is the expected output?
1. User without any permissions shouldn't be able to send any messages to admin chat
2. User without any permissions should also probably be sent an error message
3. User without any permissions really shouldn't be able to switch to admin chat in the first place.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-488 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/zq67HsRE
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/vueV44nk
3. Your townyperms.yml : https://pastebin.com/jn9beKde
4. Your log's error : I don't know what this means by "Your log's error", I'd appreciate if my ticket wasn't closed and if it was just explained in the comments for me to post.

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/hGhf68SM

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/mMdVbtV2
7. Your channels.yml : https://pastebin.com/HcM1X4LB

**Comment by LlmDl** [comment] 2019-02-06 15:39
duplicate of https://github.com/TownyAdvanced/Towny/issues/3057

**Closed by LlmDl** 2019-02-06 15:39 UTC
Labels: duplicate
