### ISSUE TITLE
Mysql database corrupt after restart.

### ISSUE THREAD

**Issue by cloakfox** [TownyAdvanced/Towny#2950] opened 2018-06-01 09:58 UTC
### What steps will reproduce the problem?
Mysql database went corrupt after a scheduled restart. After googling the errors found out it's a common issue, many others have had similair issues.

### What is the expected output?
Error: https://hastebin.com/pogiteruzu.md

### What is your Towny version?
Towny 0.92.0.0 (for mc 1.8.5)

### What is your spigot/craftbukkit version?
PaperSpigot 1431

I hope this issue can be fixed so it doesn't happen in the future.

**Comment by LlmDl** [comment] 2018-06-01 12:43
You skipped the form. Please resubmit your ticket and don't skip the form. No one's database corruption is the same as everyone else's corruption.

**Comment by cloakfox** [comment] 2018-06-01 12:45
What more info do you need?

**Comment by LlmDl** [comment] 2018-06-01 12:53
The full startup, some sort of explanation of how you think it happened, whether that's from a server crash or a special sequence of commands.

**Comment by cloakfox** [comment] 2018-06-01 13:03
Startup log: https://hastebin.com/uporamotob.md

What happened I think: I think the server crashed and towny was unable to properly save the data. Resulting in one town to corrupt. (here is what the UsingPvP table contents looked like after I deleted it to fix the issue https://hastebin.com/maqapocuce.sm)

A quick solution imo would be to automaticly delete corrupt town or playerdata and make a seperate report of that in the towny plugin folder so that it's easier to track what went wrong. Instead of forcing it in safe mode. (Not ideal on a production server). Maybe some sort of config option to toggle this.

Or fix the main issue, wich is the data corrupting

I hope this is of use to you.

Kind regards,

Cloakfox

**Comment by LlmDl** [comment] 2018-06-01 13:11
Server crashes and the mysql database don't mix very well.

I've already got about as much of the database already auto-fixing the corruption that we know we can auto-delete. Things like a mayor not being a member of a town could potentially be something we auto-fix in the future. For most servers, I don't think admins would want towny auto-deleting any towns, so safemode is how we stop people from griefing the server while protections are corrupted.

I cannot stop your server from crashing so I cannot stop the data corrupting, again consider switching to flatfile (it isn't any slower than mysql.)

Also, you shouldn't be using Towny 0.92.0.0 for MC 1.8.5 if you aren't using MC version 1.8.5. Go get the right version: http://towny.palmergames.com/?p=1070

**Comment by cloakfox** [comment] 2018-06-01 13:20
I've talked to server owners who also get these same issues using flatfile storage.

Towny is also the only plugin i've heard of that corrupts mysql data. Plugins like mcmmo, trademe, jobs, betterenderchest, & more have never corrupted on me after a server crash.

Why not try and fix the corruption issues all together, im not the only one having issues.

**Comment by KarlOfDuty** [comment] 2018-06-01 14:00
Just because they don't tell you about it doesn't mean something is corrupted, towny is just much more dependent on all information matching up than most other plugins. Towny also writes to the database much more than other plugins making it much more susceptible to errors on crashes.

We use flatfile and it is pretty simple to fix any issues that come up after certain server crashes by following what the plugin tells you to fix.

**Comment by LlmDl** [comment] 2018-06-01 14:15
@cloakfox I haven't said I won't try to fix corruption issues, I'm saying that your problem here wasn't caused by Towny, it was caused by a server crash. Lots of servers have crashes, I cannot prevent them and when it comes to mysql databases they cause corruption more often than flatfile.

**Comment by cloakfox** [comment] 2018-06-05 09:12
Happened again...This time no crash has happened, just a normal scheduled restart.

https://hastebin.com/ibariruqav.md

Again, i'm hearing stories from other owners that they have to fix their data every week. Can you guys please fix this shit.

**Comment by LlmDl** [comment] 2018-06-05 12:45
@cloakfox I need you to go back in the logs and start looking for how it happened for me. Search the logs for all instances of that player/that town. The mayor doesn't belong to town error shouldn't be happening at all and your server is the only one showing this issue and if it's not happening because of a crash I do need to know how it happens.

**Comment by cloakfox** [comment] 2018-06-10 09:43
And again. How can I fix this one in mysql?
https://hastebin.com/imemovalug.sql

**Comment by LlmDl** [comment] 2018-06-10 13:19
Your world named world has a town listed in it, which is not in the actual towns list. 

BTW, you have 9 days left to supply logs/help with figuring out what your initial issue was., before this is closed due to lack of feedback.

**Comment by cloakfox** [comment] 2018-06-10 13:38
![knipsel](https://user-images.githubusercontent.com/3696645/41202075-5107b202-6cc4-11e8-8d09-9ab9a3671d09.PNG)
These are the contents of my world folder. Now where exactly can I delete it?

**Comment by LlmDl** [comment] 2018-06-10 13:40
You need to find it in the towny mysql database, not your world folder. You might want to consider moving to using Towny in flatfile if you have trouble editing the mysql database.

**Comment by cloakfox** [comment] 2018-06-10 13:50
You should consider fixing the issues. I've already supplied enough logs and errors, and many others before me have aswell. These corruption issues have been happening for years now from what i've heard.

It's a shame that this can't run on production servers.

**Comment by LlmDl** [comment] 2018-06-10 13:52
Just because you say it, does not make it so. I have asked for your logs and your help in figuring out what happened/preceded your safe mode episodes. You have shown little ability to actually edit your own mysql database, and I have repeatedly told you to consider using flatfile instead. 

I'm closing this for good now as I'm quite sure you're just a troll and cannot possibly be serious about getting a real solution to your problems.

**Closed by LlmDl** 2018-06-10 13:52 UTC
Labels: Need Feedback

**Comment by cloakfox** [comment] 2018-06-10 13:56
I have been able to fix my mysql database for a few weeks now (same error as I initally reported), but this new error I can't seem to fix. Exact Same issues happen on flatfile. And I don't think 1200 players are going to be happy when all of their towns are gone, when I move to flatfile.

Anyway great to see you take such good care of this project. Ill ask other server owners to report the issue aswell. See if you mark them as trolls too.

**Comment by cloakfox** [comment] 2018-06-10 13:57
6 people gave my issue a +1. But hey, must be a troll right?

**Comment by LlmDl** [comment] 2018-06-10 13:58
You can convert the mysql database to flatfile and vice versa. You can farm all the likes you want from your players. If you supply the logs I asked for in a new ticket, where the form has been filled out fully, I'll look at it. You cannot expect to do less than what I need to fix an issue and get results.

**Comment by cloakfox** [comment] 2018-06-10 14:01
They are not my players, they are server owners. Instead of keep asking me to supply more shit, i've already supplied. Why not do some effort yourself and research it yourself, and find the issues & fix them.

**Comment by LlmDl** [comment] 2018-06-10 14:04
As I've said before, the initial errors you brought here I have never seen before. They are not the same error other admins have. I asked you for logs/direction so I could potentially figure out how your players managed to do this twice. You stopped responding at that point. I'm not going to waste my time guessing how you managed to do something I have never seen happen before.

**Comment by cloakfox** [comment] 2018-06-10 14:06
[2018-06-04-2.log.gz](https://github.com/TownyAdvanced/Towny/files/2087930/2018-06-04-2.log.gz)
[2018-06-04-12.log.gz](https://github.com/TownyAdvanced/Towny/files/2087931/2018-06-04-12.log.gz)

[2018-06-10-1.log.gz](https://github.com/TownyAdvanced/Towny/files/2087932/2018-06-10-1.log.gz)
[2018-06-09-2.log.gz](https://github.com/TownyAdvanced/Towny/files/2087933/2018-06-09-2.log.gz)


Here you go.

**Comment by LlmDl** [comment] 2018-06-10 14:07
Great I'll make sure that I get around to this when I'm not as annoyed/insulted.

**Comment by cloakfox** [comment] 2018-06-10 14:08
Thanks.
