### ISSUE TITLE
Double Chat when using DeluxeChat

### ISSUE THREAD

**Issue by 0liverGMC** [TownyAdvanced/Towny#4118] opened 2020-06-28 04:51 UTC
### What steps will reproduce the problem?
1. Using DeluxeChat with Towny, TownyChat, and TownyNameUpdater
2.
3.

### What is the expected output?
1. A single chat from DeluxeChat, but receives two separate chats
2.
3.

### What is your Towny version?
0.96.2.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-1 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/xuwihebeve.shell
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/utukotaral.coffeescript
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://hastebin.com/itohenanuz.shell
7. Your channels.yml : https://hastebin.com/etalidakax.bash

**Comment by 0liverGMC** [comment] 2020-06-28 04:51
Here is a screenshot of what happens https://i.mineadia.com/aOYOaXLK8x.png

**Comment by LlmDl** [comment] 2020-06-28 05:04
This is likely due to TownyChat fixing a bug which has made DeluxeChat's use of the TownyChat API insufficient. I have tried to contact clip about this but no word back yet. You can use TownyChat 0.69 or 0.68 in the meantime.

**Comment by 0liverGMC** [comment] 2020-06-28 06:02
Yea 0.69 is working fine, clip seems to be busy updating his whole suite of plugins so it seems understandable that it may take a while. Thanks regardless for the quick response!

**Comment by LlmDl** [comment] 2020-07-03 22:25
Duplicate of #4057

**Closed by LlmDl** 2020-07-03 22:25 UTC
Labels: Label-Chat, bug
