### ISSUE TITLE
Minecarts invunerable to cacti damage

### ISSUE THREAD

**Issue by bretomart** [TownyAdvanced/Towny#4564] opened 2020-12-10 13:04 UTC
### What steps will reproduce the problem?
1. Installation TownyAdvanced 0.96.5.0
2.
3.

### What is the expected output?
1. When minecarts are set on a rail on a downward trajectory coming in collision with cacti they remain in tact and undamaged.
2. No trajectory changes or speed changes affect this.
3. This is not the case outside of town borders. Minecarts do get damage in the wilderness, so it's isolated to town claimed plots.

### What is your Towny version?
Do not say "latest".
0.96.5.0

### What is your spigot/craftbukkit version?
Do not say "latest".
paper-1.16.4-322

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/2b9HcikJ
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/276R1Xah
3. Your townyperms.yml : https://pastebin.com/V4VREKjV
4. Your log's error : NA

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment] 2020-12-10 13:06
Momshroom beat you to it last night, and I've fixed this one. It will be part of 0.96.5.5.

**Comment by LlmDl** [comment] 2020-12-10 13:06
Duplicate of #4561

**Closed by LlmDl** 2020-12-10 13:06 UTC
Labels: bug
