### ISSUE TITLE
Suggestion:  Alliance

### ISSUE THREAD

**Issue by mikk475i** [TownyAdvanced/Towny#4798] opened 2021-03-11 16:53 UTC
**Please explain your feature request to the best of your abilities:**
Would it be possible to make a town able to ally another town and make pacts such as non-aggressive

**Comment by LlmDl** [comment] 2021-03-11 17:02
Duplicate of https://github.com/TownyAdvanced/Towny/issues/3476

**Closed by LlmDl** 2021-03-11 17:02 UTC
Labels: duplicate, enhancement
