### ISSUE TITLE
Suggestion: Add the ability for a nation to transfer ownership of a town to another nation

### ISSUE THREAD

**Issue by Vanstredam** [TownyAdvanced/Towny#4906] opened 2021-05-05 19:46 UTC
My idea is to add a command that can transfer a town from one nation to another through both default and admin methods, for example:

- [ ] Players could run a command /n transfer {town name} {nation you want to transfer the town to}
- [x] Admins could have a command such as /ta nation {nation} transfer {town name} {nation you want to transfer the town to}

It would be useful for nations breaking into smaller ones who have inactive towns inside them, as I don't think people will generally have the patience to wait for someone to get on to accept their invite or have to siege them for it, plus it's a more peaceful way of disintegrating large nations.

It should also be optional in config.yml as well.

**Comment by Warriorrrr** [comment] 2021-05-05 20:39
Duplicate of #4796, this issue is more detailed so I'll leave this one open and close the other.

**Closed** 2023-07-24 22:28 UTC
Labels: enhancement, Priority-Low, Label-Nations, Label-Command
