### ISSUE TITLE
Towny Name Updater not working

### ISSUE THREAD

**Issue by slvlr** [TownyAdvanced/Towny#3244] opened 2019-05-07 18:49 UTC
### What steps will reproduce the problem?
1. User changed name from Huxneeb to VikingGoddess

### What is the expected output?
1. Huxneeb to no longer be Town mayor and VikingGoddess to be Mayor. 
2. Name is not updating - Server IP  Lonksmc.gamename.net 

### What is your Towny version?
Towny 0.93.0.0
Towny Chat 0.53
Towny Name Update 2.0

### What is your spigot/craftbukkit version?
Paperspigot 1.13.2 - 597

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hasteb.in/otuyuzax.md
2. Your Towny config.yml :  https://hasteb.in/zisomefu.coffeescript
3. Your townyperms.yml : https://hasteb.in/uxocoyus.yaml
4. Your log's error :  No error 

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

**Comment by Articdive** [comment] 2019-05-23 18:08
@slvlr could you give me a version of your playermap.yml in the dataFolder of Towny?

**Comment by slvlr** [comment] 2019-05-23 18:11
@Articdive  https://pastebin.com/r4ztcgz6

**Comment by Articdive** [comment] 2019-05-23 18:28
Are you sure, that it didn't update it?, it did in what you sent me.

**Comment by Articdive** [comment] 2019-05-23 18:28
Or was it only after it logged in for the second time?

**Comment by slvlr** [comment] 2019-05-23 18:36
@Articdive It only updated this user as they were complaining about how long it took, I had to delete the old user and change the owner of the town by admin commands.

**Comment by Articdive** [comment] 2019-05-23 19:34
did you get any stacktraces (errors)?, your log on hastebin has long been expired.

**Comment by Articdive** [comment] 2019-05-23 19:35
I might know what the error is, but would need a log to confirm

**Comment by slvlr** [comment] 2019-05-23 19:36
which file would this error be in? I haven't had a player change their name since this report 16 days ago.

**Comment by Articdive** [comment] 2019-05-23 19:59
the log file from the day it happend, or at least try to find an instance (if you can) where this has happended before.

**Comment by Articdive** [comment] 2019-05-23 20:01
anything with an "AlreadyRegisteredException" in the logs could be gold for this case.

**Comment by slvlr** [comment] 2019-06-22 11:11
I really can't find anything, and I am having this issue again as more players have changed their name. Please could you message me on discord? Rangewonk / SlVlR#9222

**Comment by JohnS19** [comment] 2019-07-02 22:01
https://hasteb.in/xujevaxu.md

**Comment by Articdive** [comment] 2019-07-26 07:18
Ok, in TownyNameUpdater 3.0 (not released yet) I might have addressed this issue, it still requires testing since I'm unable to reproduce it.
Closing this @LlmDl,
Comment here pinging either LlmDl or me And we'll reopen it if it's still the case

**Closed by Articdive** 2019-07-26 07:18 UTC

**Comment by LlmDl** [comment] 2019-07-26 16:14
For those you on 0.94.0.2 or newer: https://github.com/TownyAdvanced/TownyNameUpdater/releases/tag/3.0

For those of you on 0.94.0.0 or older:
https://github.com/TownyAdvanced/TownyNameUpdater/releases/tag/2.5

**Comment by slvlr** [comment] 2019-08-12 14:50
@LlmDl I get this error and it still does not work.


12.08 10:49:24 [Server] ERROR Could not pass event PlayerLoginEvent to TownyNameUpdater v3.0
12.08 10:49:24 [Server] INFO java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/TownyUniverse
12.08 10:49:24 [Server] INFO at com.palmergames.townynameupdater.TownyNameUpdater.onJoin(TownyNameUpdater.java:38) ~[?:?]
12.08 10:49:24 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor966.execute(Unknown Source) ~[?:?]
12.08 10:49:24 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.attemptLogin(PlayerList.java:545) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:154) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
12.08 10:49:24 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.towny.TownyUniverse
12.08 10:49:24 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
12.08 10:49:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-167]
12.08 10:49:24 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
12.08 10:49:24 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]

**Comment by LlmDl** [comment] 2019-08-12 15:36
@slvlr you're using the TNU for the Towny builds with the new API, which you aren't using.

https://github.com/TownyAdvanced/TownyNameUpdater/releases

Get the one marked Legacy. It'll be TNU 2.5.

**Comment by slvlr** [comment] 2019-08-12 15:55
@LlmDl I am using Towny 0.94.0.0 on Minecraft 1.14.4 -  Where Do I get the newer Towny builds? Is it worth updating?

**Comment by LlmDl** [comment] 2019-08-12 15:58
You can find 0.94.0.4 on the discord's #new_builds channel. It's got stuff, but might not be super stable. It does have stuff for 1.14. If you use that build you will want to keep your TNU 3.0.

**Comment by slvlr** [comment] 2019-08-12 16:05
If I update to 0.94.0.4 do I need to update Townychat too?

**Comment by LlmDl** [comment] 2019-08-12 16:12
Yes, there's a release for it on the TownyChat repo releases page, 0.56
