### ISSUE TITLE
Suggestion: Dynmap icon for ruined towns

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5035] opened 2021-06-29 06:19 UTC
**Please explain your feature request to the best of your abilities:**

It would be nice to have a Dynmap icon for ruined towns.  This would help players to identify them on the map, and either reclaim them or loot them.

**Comment by LlmDl** [comment] 2021-06-29 12:49
This was added semi-recently, not yet released. Duplicate of https://github.com/TownyAdvanced/Towny/issues/5026

**Closed by LlmDl** 2021-06-29 12:49 UTC
Labels: enhancement

**Comment by MilesBHuff** [comment] 2021-06-29 14:25
Oh awesome!  And sorry;  I must have forgotten to remove the open-only filter when I searched to make sure I wasn't making a duplicate.
