### ISSUE TITLE
A problem with towny removing all claimed chunks physically. The data still exists when /t is issued

### ISSUE THREAD

**Issue by Muikkumies** [TownyAdvanced/Towny#3813] opened 2020-03-22 16:02 UTC
### What steps will reproduce the problem?
Might not be reproducable. Error has to do with dynmap-towny
1. Claim a town area
2. Stop server
3. Start server

### What is the expected output?
1. Server is expected to start normally and players are supposed to have their towny claimed just as  before

### What is your Towny version?
 0.96.0.0

### What is your spigot/craftbukkit version?
Papermc build 143

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : 
[latest.log](https://github.com/TownyAdvanced/Towny/files/4365510/latest.log)

2. Your Towny config.yml (if using MySQL please remove password,) :
[config.txt](https://github.com/TownyAdvanced/Towny/files/4365511/config.txt)

3. Your townyperms.yml :
[townyperms.txt](https://github.com/TownyAdvanced/Towny/files/4365514/townyperms.txt)

4. Your log's error : 
[15:34:14] [Server thread/INFO]: [Dynmap-Towny] Enabling Dynmap-Towny v0.75
[15:34:14] [Server thread/INFO]: [Dynmap-Towny] initializing
[15:34:14] [Server thread/ERROR]: Error occurred while enabling Dynmap-Towny v0.75 (Is it up to date?)
java.lang.NoClassDefFoundError: com/palmergames/bukkit/TownyChat/Chat
	at org.dynmap.towny.DynmapTownyPlugin.onEnable(DynmapTownyPlugin.java:880) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.ClassNotFoundException: com.palmergames.bukkit.TownyChat.Chat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-143]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_77]
	... 10 more
[15:34:14] [Server thread/INFO]: [Dynmap-Towny] Disabling Dynmap-Towny v0.75

**Comment by LlmDl** [comment] 2020-04-04 15:01
I am marking this ticket as a duplicate of [the earliest ticket](https://github.com/TownyAdvanced/Towny/issues/3783) filed for this problem, as no one has said they are still experiencing the issue since 0.96.1.1 was put out.

**Closed by LlmDl** 2020-04-04 15:01 UTC
Labels: bug, duplicate
