### ISSUE TITLE
Suggestion: Bank History

### ISSUE THREAD

**Issue by PrinceOSpace** [TownyAdvanced/Towny#4108] opened 2020-06-22 19:05 UTC
**Please explain your feature request to the best of your abilities:**
The addition would be the ability for certain ranks of town members (mayor, co-mayors, assistants) to be able to check the history of bank deposits and withdrawals. These history reports could name the players, whether they deposited or withdrew from the bank, the amount of money, and possibly a timestamp.

**Comment by docwhomc** [comment] 2020-06-22 20:18
I think this would be doable, provided (1) an economy plugin has implemented or implements the recording of transactions to a database and (2) the Vault API has or adds a means of querying such a database.

**Comment by docwhomc** [comment] 2020-06-22 20:20
I wasn't able to find a plugin to satisfy requirement (1) and I didn't see any indication that requirement (2) has been satisfied when I skimmed the Vault API, but maybe I missed something.

**Comment by suneettipirneni** [comment] 2020-06-22 20:22
I’ve added an auditing system to the bank PR that is en route. This doesn’t provide any user features yet but provides a system for hooking into whenever a transaction occurs to a given town/nation account so we can build on top of this API in the future.

**Comment by docwhomc** [comment] 2020-06-22 20:47
Which PR is that?

**Comment by suneettipirneni** [comment] 2020-06-22 20:48
@docwhomc #3988

**Comment by LlmDl** [comment] 2020-06-22 21:27
Duplicate of https://github.com/TownyAdvanced/Towny/issues/2670

**Closed** 2020-06-22 21:27 UTC
Labels: duplicate, enhancement
