### ISSUE TITLE
Town claims being unclaimed after restart

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/Towny#3796] opened 2020-03-19 03:31 UTC
### What steps will reproduce the problem?
1. Claim land for your town
2. Wait for a restart
3. Some claims are not saved after a restart

### What is the expected output?
1. Claim land for your town
2. Wait for a restart
3. Claims are all saved after a restart

### What is your Towny version?
0.95.2.20

### What is your spigot/craftbukkit version?
Tuinity-daa949d (MC 1.15.2)

### Please use Pastebin.com to link the following files:

Logs of everything user did in between claiming and the present:
https://paste.gg/p/anonymous/96bac0921a5a4f87ac8dccd76d4417d4

Entire log of 2020-03-15-3:
https://paste.gg/p/anonymous/09d6ea4138f34158bb7a58ca4cde7de0

Entire Log of 2020-03-16-1:
https://paste.gg/p/anonymous/4b18fd8700d04d7b921ff58b9380324b

Entire Log of 2020-03-16-2:
https://paste.gg/p/anonymous/fe2929628a9444fc8e2398847e7bc64b

The claims were made in 2020-15-3, the restart occurred between 2020-03-16-1 and 2020-03-16-2.

config.yml:
https://paste.gg/p/anonymous/f1e52ed707a941f4ab8ad6c866c0e2fe

townyperms.yml:
https://paste.gg/p/anonymous/14e3babe48664e7fb7eeda2dabb0c4e3

### Additional Information

User claimed an island. After restart, seemingly randomly some of the regions were unclaimed. This has happened many times, and I know many are experiencing this, so hopefully this information helps! I have more documented cases, but this was the simplest since this user was the only one who was in the town, and they never ran a single unclaim command. As you can see, the restarts were graceful and ran by doing /stop.

![image](https://user-images.githubusercontent.com/42015460/77028902-9416d780-6970-11ea-837b-bb1e20afd680.png)

This image shows the claims after the restart. Prior to restart, this island was completely claimed.

**Comment by Emperor-Koala** [comment] 2020-03-30 22:09
If you don't mine me commenting here, our server just encountered the same issue. I don't have much to contribute other than the log files we have from the past two days since installing Towny. I've trimmed out a bunch of unnecessary lines from those logs (AreaShop plugin likes to throw NPE and ClassCastException). The logs can be found here: https://pastebin.com/3z6q2cJG

**Comment by LlmDl** [comment] 2020-04-02 20:36
The [pre-release version 0.96.1.1](https://github.com/TownyAdvanced/Towny/releases/tag/0.96.1.1) has what I believe to be a solution to the issue of vanishing TownBlocks described in your ticket. I would appreciate it if you would consider updating to 0.96.1.1 and letting me know if you have any more vanishing TownBlocks.

**Comment by LlmDl** [comment] 2020-04-04 15:02
I am marking this ticket as a duplicate of [the earliest ticket](https://github.com/TownyAdvanced/Towny/issues/3783) filed for this problem, as no one has said they are still experiencing the issue since 0.96.1.1 was put out.

**Closed by LlmDl** 2020-04-04 15:02 UTC
Labels: bug, duplicate
