### ISSUE TITLE
Revert on Unclaim - No 1.13-Items are supported

### ISSUE THREAD

**Issue by Effendil** [TownyAdvanced/Towny#3031] opened 2018-09-12 15:29 UTC
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. /t Claim 
2. Place some new item from 1.13
3. /t unclaim

### What is the expected output?
1. All blocks i placed get regenerated because i enbale revert on unclaim
2.
3.

### What is your Towny version?
0.93.0.0

### What is your spigot/craftbukkit version?
spigot-1.13.1-R0.1-SNAPSHOT-b1907

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/RwZYAu5S
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/RF2f1Afw
3. Your townyperms.yml : totally vanilla i dont do anything on this file
4. Your log's error : Theres no Errors so i cant post anything here -.-

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment] 2018-09-12 15:31
I think this is a duplicate of this: https://github.com/TownyAdvanced/Towny/issues/3010

**Closed by LlmDl** 2018-09-12 15:31 UTC
