### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by OLdGoogol** [TownyAdvanced/Towny#4683] opened 2021-01-11 01:34 UTC
**Please explain your feature request to the best of your abilities:**

A maximum distance between a town's homeblock and its outposts. 

I tried to find this feature in config.yml, but i failed.
This can prevent players from producing very "ugly" territory when observered from dynmap.

**Comment by LlmDl** [comment] 2021-01-11 02:39
1. Already exists:
```
  # The maximum number of townblocks a town can be away from a nation capital,
  # Automatically precludes towns from one world joining a nation in another world.
  # If the number is 0, towns will not a proximity to a nation.
  nation_requires_proximity: '0.0'
```
2. is a ticket already suggested on here as a duplicate of https://github.com/TownyAdvanced/Towny/issues/3065.

**Closed by LlmDl** 2021-01-11 02:39 UTC
Labels: enhancement
