### ISSUE TITLE
Leaderboard Placeholder does not recognize town names including a space/underscore 

### ISSUE THREAD

**Issue by NiftySMP** [TownyAdvanced/Towny#6990] opened 2023-09-16 02:38 UTC
### What steps will reproduce the problem?

1. Make your town have highest balance
2. Set town name to 'Test Name'
3. /papi parse me %townyadvanced_top_town_balance_1%
4. Check **Result (1)** 
5. Set town name to 'TestName'
6. /papi parse me %townyadvanced_top_town_balance_1%
4. Check **Result (2)** 

### What is the expected output?

**Result (1):** <Blank> 
**Result (2):** TestName - $######

### Towny version

0.99.5.0

### Server version

Paper version git-Paper-174 (MC: 1.20.1)

### Please use Pastebin.com to link the following files

https://pastebin.com/rg2Jaqtk

No errors; Pretty sure its just a placeholder bug.

**Comment by Warriorrrr** [comment] 2023-09-16 02:42
Duplicate of #6814, update to the latest pre-release which has the fix

**Closed by Warriorrrr** 2023-09-16 02:42 UTC
Labels: bug
