### ISSUE TITLE
Suggestion: Unset nation spawn if the capital falls

### ISSUE THREAD

**Issue by gabeeebaby** [TownyAdvanced/Towny#4987] opened 2021-06-04 18:52 UTC
**Please explain your feature request to the best of your abilities:**
Currently when the capital of the nation falls, but other towns in the nation still exist, the nation spawn ends up being in the wilderness. This can confuse players and cause possible "spawn traps". Perhaps when a nation capital falls, the spawn is unset, and the new king must set it in the new capital.

**Comment by Warriorrrr** [comment] 2021-06-04 18:59
Duplicate of #4961

**Closed by Warriorrrr** 2021-06-04 18:59 UTC
Labels: enhancement
