### ISSUE TITLE
Dynmap Towny Error

### ISSUE THREAD

**Issue by zek2468** [TownyAdvanced/Towny#4074] opened 2020-06-11 23:25 UTC
### What steps will reproduce the problem?
1. Install Dynmap-Towny v0.80 stable
2. install Dynmap v3.0.1 Stable
3. Install Towny v0.96.1.0 stable
4. check console for exception

### What is the expected output?
1. No Errors on console

### What is your Towny version?
Towny v0.96.1.0 stable

### What is your spigot/craftbukkit version?
1.15.2 Paper #348 Stable

Dynmap version
3.0.1 stable

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
     https://pastebin.com/raw/1x2KaYcP
2. Your Towny config.yml (if using MySQL please remove password,) :
    https://pastebin.com/raw/bp85nd2a
3. Your townyperms.yml :
    https://pastebin.com/raw/Qw4GQGNZ
4. Your log's error : 
    https://pastebin.com/raw/LypDQj3Q

**Comment by LlmDl** [comment] 2020-06-12 00:21
Duplicate of https://github.com/TownyAdvanced/Towny/issues/4007

**Closed by LlmDl** 2020-06-12 00:21 UTC
Labels: bug, duplicate
