### ISSUE TITLE
Way to merge towns

### ISSUE THREAD

**Issue by karlovm** [TownyAdvanced/Towny#4060] opened 2020-06-07 15:10 UTC
Is there a simple way to merge towns to one via Towny?

I need it for my wars plugin,

**Comment by ZenArchipelago** [comment] 2020-06-07 15:31
Do you mean like annex a town, because in that case there is a plug-in known as War For Towny on spigot which can do that.

**Comment by suneettipirneni** [comment] 2020-06-07 16:02
If you’re talking about merging two towns into one expect that very soon.

**Comment by LlmDl** [comment] 2020-06-07 17:43
Duplicate of https://github.com/TownyAdvanced/Towny/issues/3193

**Closed by LlmDl** 2020-06-07 17:43 UTC
Labels: question
