### ISSUE TITLE
Suggestion: Remove max duration for the ruin timer

### ISSUE THREAD

**Issue by ArtamaMeyer** [TownyAdvanced/Towny#5031] opened 2021-06-27 09:16 UTC
# This value determines the maximum duration in which a town can lie in ruins
    # After this time is reached, the town will be completely deleted.
    # Does not accept values greater than 1000.
    max_duration_hours: '72' 

Id like an option to make the max duration infinite for example -1 or 99999999

**Comment by LlmDl** [comment] 2021-06-27 14:54
Duplicate of #4970

**Closed by LlmDl** 2021-06-27 14:54 UTC
Labels: enhancement
