### ISSUE TITLE
TownyAdvanced | PVP doesn't turn on automatically during a nation is under attack (Flag War)

### ISSUE THREAD

**Issue by AdamDoesStuff** [TownyAdvanced/Towny#4709] opened 2021-01-21 02:32 UTC
### What steps will reproduce the problem?
1. A Nation attacks another Nation by placing a flag
2. Attacking Nation cannot hit defending Nation inside claims
3. Defending nation is immune inside of claims

### What is the expected output?
1. Nation attacks another Nation by placing a flag
2. Attacking Nation starts defending the flag they placed down and can pvp in any area (even claims).
3. War keeps on going as normal

### What is your Towny version?
Do not say "latest". 0.96.5.0

### What is your spigot/craftbukkit version?
Do not say "latest". Paper 1.16.3 #229

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/C81xu4Hq (Password) GitHubTowny (i can't make it public for some reason)
3. Your townyperms.yml : https://pastebin.com/xaaDy6Rd (same as otherone)

**Comment by LlmDl** [comment] 2021-01-21 13:11
This is a duplicate of this: https://github.com/TownyAdvanced/Towny/issues/4279

It is something that has already been fixed in the [damage events pr](https://github.com/TownyAdvanced/Towny/pull/4566/files#diff-31cd9ee5ffb0008587edd11cf1050d04a893113153c476e45a143c3e4b99fb16).

**Closed** 2021-01-29 16:22 UTC
Labels: Completed, Flag War, bug, duplicate
