### ISSUE TITLE
When an attachable block is blown up by an explosion, it drops, but also regenerates, duplicating it.

### ISSUE THREAD

**Issue by blockutis** [TownyAdvanced/Towny#7154] opened 2024-01-01 02:17 UTC
### What steps will reproduce the problem?

1. Start the server, with no other plugins installed
2. Create a small platform (3x3) of blocks, such as dirt.
3. Place attachable blocks on top of the platform such as lanterns, torches, carpets, flowers, crops, redstone components.
4. Spawn a creeper or place a tnt on top of the center block
5. Light the creeper/tnt with a flint and steel
6. The attachable blocks will drop, but also regenerate after a few seconds.
Screenshot: 
![image](https://github.com/TownyAdvanced/Towny/assets/105829769/87c2859b-ac9f-47b3-9f7a-19a90f545b7b)

### What is the expected output?

The blocks do not both drop AND regenerate

### Towny version

Towny Version: 0.100.0.0

### Server version

Paper version git-Paper-365 (MC: 1.20.4)

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: [latest.log](https://pastebin.com/idc0Uf60)
2. Your Towny config.yml: [config.yml](https://pastebin.com/Zb2mq4X4)
3. Your townyperms.yml: [townyperms.yml](https://pastebin.com/aQyxnyHC)
4. Your log's error: N/A

**Comment by Warriorrrr** [comment] 2024-01-03 10:37
Is there any block that should be protected but isn't? otherwise this is just a duplicate of #5689

**Comment by LlmDl** [comment] 2024-01-03 15:03
@Warriorrrr I have been seeking better instructions on how to make it happen as I could not reproduce any duping on my test server, so I couldn't really begin to solve it.

**Closed** 2024-01-08 22:40 UTC
Labels: bug, Completed
