### ISSUE TITLE
Suggestion: Make jobs that a town or nation pay for.

### ISSUE THREAD

**Issue by ArvidGreat** [TownyAdvanced/Towny#4823] opened 2021-03-21 12:39 UTC
So, If you ever have played on a towny server before you might have noticed that its only mayors and assistants that is active. All residents no where to be seen. They have eighter made their own town and quit the server after making a awfull house on a plot. 

I belive that this problems comes from that residents don't feel they have anything else to do than just build a house and quit, like what more is there to it?

To fix this problem to make towny better i suggest that in the spirit of siegewar make ranks, ( well more jobs) that the town or nation pay for. 

Assisstants and above can give the ranks of Farmer, miner, forester, hunter and any other job the owner might want to add themselves. This might sound a bit like jobs the plugin and it should. Jobs pay only scraps for work to begin with but with the addition with towny it would give said player more income to build a more stable server economy overall. it would make the town feel like a corporation, something you invest in somethingyou work for. 

A nationalistic feeling to the town and nation.

My server have that food rotts and diseases and other things gives importance to residents becouse they can make an impact. All farmers in a town would get paid by the town, paid by the plugin jobs and would be able to sell their produce. with the addition of that food rotts gives much importance to a farmer, It makes normal residents involved becouse they make the server run without a famine.

The idea is to give residents importance becouse right now they are worthless just a number and a plot with a shitty house and nothing more.  This feature could make it somewhat rewarding and fun to just be a nobody and keep residents active in a town, becouse what is the meaning of a town when only they mayor and his righthandman is the only one playing and gives a shit about the town?

**Comment by LlmDl** [comment] 2021-03-21 13:41
Duplicate of https://github.com/TownyAdvanced/Towny/issues/2447

**Closed by LlmDl** 2021-03-21 13:41 UTC
Labels: enhancement
