### ISSUE TITLE
Suggestion: Audit log

### ISSUE THREAD

**Issue by bonnedav** [TownyAdvanced/Towny#3168] opened 2019-02-02 09:51 UTC
Add a log of /town and /plot command usage that mayors can look at to see who did what and when.
This would give mayors a better idea of what goes on when there offline and let them keep better control over the town by letting them see if town staff are abusing there powers. Mayors can only see /town and /plot usage relating to there town. Server admins/mods can see the full log.

**Comment by Articdive** [comment] 2019-07-26 07:20
This could actually be done using a Log4j2 logger for every town, it would also be an amazing admin tool to see what commands are run per town.
Would require maven to add log4j2 support to Towny though.

**Comment by LlmDl** [comment] 2019-08-09 22:07
Well we have maven and a new logger now.

**Comment by LlmDl** [comment] 2020-06-22 21:28
This one turns out is a duplicate of https://github.com/TownyAdvanced/Towny/issues/2670

**Closed by LlmDl** 2020-06-22 21:28 UTC
Labels: enhancement

**Comment by bonnedav** [comment] 2020-06-22 23:40
Has something like this been implemented yet? I for one would still like to see it.

**Comment by docwhomc** [comment] 2020-06-22 23:56
@bonnedav
> This one turns out is a duplicate of #2670

**Comment by LlmDl** [comment] 2020-06-23 00:06
There's been about 1/2 the work laid out for the bank logging. Command logging has not begun but would eventually be possible.
