### ISSUE TITLE
/Towny Prices triggers internal error

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/Towny#5819] opened 2022-03-19 17:49 UTC
### What steps will reproduce the problem?

start the server
use /towny prices

### What is the expected output?

A list with the prices

### Towny version

0.98.1.0

### Server version

git-Paper-235

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log:
[latest.log](https://github.com/TownyAdvanced/Towny/files/8309800/latest.log)

2. Your Towny config.yml: 
[config.txt](https://github.com/TownyAdvanced/Towny/files/8309801/config.txt)

3. Your townyperms.yml:
[townyperms.txt](https://github.com/TownyAdvanced/Towny/files/8309803/townyperms.txt)

4. Your log's error: https://pastebin.com/vbA4Dh8V

**Comment by LlmDl** [comment] 2022-03-19 17:59
Do you use a custom es-ES.yml in your towny\settings\lang\override folder?

**Comment by ElMoha943** [comment] 2022-03-19 18:07
No, te one that comes with the plugin

**Comment by LlmDl** [comment] 2022-03-19 18:08
And you haven't put anything in your towny\settings\lang\override\global.yml? 

What locale is your client using?

**Comment by ElMoha943** [comment] 2022-03-19 18:09
Havent touch any lang files. My game is in english, maybe there is an error in es-ES

**Comment by LlmDl** [comment] 2022-03-19 18:10
The es-ES and en-US files are fine for the language string involved. 

Whatever client locale is set to is the language file Towny uses.

I am unable to reproduce this error on 0.98.1.2.

**Comment by ElMoha943** [comment] 2022-03-19 18:11
> Whatever client locale is set to is the language file Towny uses.
Can i make towny override this an just use es-ES?

**Comment by ElMoha943** [comment] 2022-03-19 18:13
Changed this
![imagen](https://user-images.githubusercontent.com/25410859/159133417-9afeb775-5939-492d-933b-8ac33f158e08.png)
but still problem persists

**Comment by LlmDl** [comment] 2022-03-19 18:14
Show me your es-ES.yml from teh towny\settings\lang\reference\ folder.

**Comment by ElMoha943** [comment] 2022-03-19 18:15
[es-ES.txt](https://github.com/TownyAdvanced/Towny/files/8309846/es-ES.txt)
Note: sent as txt bc git doesnt allow yml

**Comment by LlmDl** [comment] 2022-03-19 18:18
Ok, I spotted it this time, the String that fails started with a % instead of a &. This will be fixed as of 0.98.1.3.

**Closed by LlmDl** 2022-03-19 18:18 UTC
Labels: bug

**Comment by ElMoha943** [comment] 2022-03-19 18:21
Thanx you!
Mind telling me wich line exactly so i can fix it in my server meanwhile?
![imagen](https://user-images.githubusercontent.com/25410859/159133715-e6f71b1c-d109-4e23-a073-47c48d56549b.png)

**Comment by LlmDl** [comment] 2022-03-19 18:22
towny_prices_nation_upkeep_based_on

**Comment by ElMoha943** [comment] 2022-03-19 18:24
> towny_prices_nation_upkeep_based_on

Changed the % for a &, did a /ta reload all and it persists, but ig i should restart the whole server and try then right?

**Comment by LlmDl** [comment] 2022-03-19 18:25
Put your language file into the towny\settings\lang\override folder.

**Comment by ElMoha943** [comment] 2022-03-19 18:28
> Put your language file into the towny\settings\lang\override folder.

Fixed! thanx!
