### ISSUE TITLE
Suggestion: "Trusted" feature for towns and towny perms

### ISSUE THREAD

**Issue by GeneralDarian** [TownyAdvanced/Towny#4981] opened 2021-06-02 15:54 UTC
**Please explain your feature request to the best of your abilities:**
On my server people frequently help other towns with builds or items despite being in other nations. It would be really nice if there was a trusted option which towns could have. That way, if you want to give someone, say, full build access to your town, you don't have to add them as a friend and then claim ownership of every single plot in the town, which can be quite a nuisance. 

You can add someone on the "trusted" list as a mayor by running the command /t trusted add (username)
Then you can give them, say, full build perms in the town with the command /t set perm trusted build on 
To view the trusted list anyone (including residents) can do /t trusted
And to remove someone from the trusted list the mayor can do /t trusted remove (username)

This would also be useful if you want to only give certain residents of your town and/or nation access to a plot for whatever reason

**Comment by LlmDl** [comment] 2021-06-02 16:33
I believe this would be a duplicate of https://github.com/TownyAdvanced/Towny/issues/4117, please advise.

**Comment by GeneralDarian** [comment] 2021-06-02 17:31
It's a bit similar but not exactly the same, #4117 actually adds this feature as various ranks which you can assign to users that aren't in your town but I think it would be easier to just have a whitelist-like option which you can add users to, regardless if they are in your nation, town, or neither, and then the entire whitelist acts like its own permission option

**Comment by LlmDl** [comment] 2021-06-02 17:37
Their ticket originally asked for ranks, but Towny is not coded that way. This ticket is closer to what I had in mind with the other ticket, aside from needing to turn on Trusted with /t set perm. My thinking is if they're in the trusted list they are trusted and treated as a resident of the town instead of an outside/ally/nation.

If a Trusted PermGroup were added it would have to use a different word that doesn't start with T (because Town is already on the perm lines represented by T.)

I'm closing #4117 in favour of this ticket for the time being.

**Comment by GeneralDarian** [comment] 2021-06-02 19:24
> Their ticket originally asked for ranks, but Towny is not coded that way. This ticket is closer to what I had in mind with the other ticket, aside from needing to turn on Trusted with /t set perm. My thinking is if they're in the trusted list they are trusted and treated as a resident of the town instead of an outside/ally/nation.

This could work well, but maybe (as an example) a town has certain buildings or areas of the town which they only want residents to access, and if residents and trusted people are in the same group managing the permissions for this is kind of a nuisance. Thus having them be separate roles would be better imo.

 > If a Trusted PermGroup were added it would have to use a different word that doesn't start with T (because Town is already on the perm lines represented by T.)

Maybe diplomat or ambassador? Would make sense and it fits in with embassy plots as well...

**Closed** 2021-07-17 20:11 UTC
Labels: Completed, Label-Towns, enhancement
