### ISSUE TITLE
TownyChat - Send message when not in nation

### ISSUE THREAD

**Issue by MrWardy** [TownyAdvanced/Towny#3175] opened 2019-02-06 01:52 UTC
I've been setting up TownyChat and realized when you aren't in a nation and attempt to use nation chat it simply does nothing in chat. I think there should be a message, preferably configurable, saying something like "You must be in a nation to use nation chat" or something along those lines. I think this could prevent a lot of confusion amongst players.

**Comment by LlmDl** [comment] 2019-04-16 13:26
I think this is probably a bug related to another bug:
https://github.com/TownyAdvanced/Towny/issues/3057

**Comment by LlmDl** [comment] 2019-05-25 15:11
Closing this, as it is a duplicate of the above ticket, which has better notes.

**Closed by LlmDl** 2019-05-25 15:11 UTC
Labels: Label-Chat, bug
