### ISSUE TITLE
Suggestion: /t merge

### ISSUE THREAD

**Issue by johnyuki** [TownyAdvanced/Towny#4782] opened 2021-03-02 03:37 UTC
**Please explain your feature request to the best of your abilities:**

Would work in the same way `/n merge` does, but `/t merge` would merge towns instead.

**Comment by LlmDl** [comment] 2021-03-02 12:26
Duplicate of #3193 and already being solved in the coming PR #4755

**Closed by LlmDl** 2021-03-02 12:26 UTC
Labels: enhancement
