### ISSUE TITLE
Towny Flag War issues: Local PVP settings overriding FlagWar

### ISSUE THREAD

**Issue by Schnitzengruber** [TownyAdvanced/Towny#4279] opened 2020-08-21 00:18 UTC
### What steps will reproduce the problem?
1. A towny nation will declare on another (non-neutral) nation and go to flag them 
2. The defending nation will have PVP turned off, so players can't pvp during a flagwar
3. The attackers are also not allowed to build fences in the defending towns.

### What is the expected output?
1. nations declare war
2. players show up and can pvp with others in town territory
3. Attackers in a flag war can place flags in others territory to take it

### What is your Towny version?
Do not say "latest".

### What is your spigot/craftbukkit version?
Do not say "latest".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Schnitzengruber** [comment] 2020-08-21 00:31
Version: 0.96.2.0
Paper version: 1.16.1
Startup: https://pastebin.com/RkJQXyxN
Towny config: https://pastebin.com/Ek0NJNsS
Towny perms: https://pastebin.com/Ehq083m7
- No log error -

5. towny permissions allowed:
- towny.town.spawn.town
- towny.command.town.toggle.pvp
- towny.wild.*

**Comment by LlmDl** [comment] 2020-08-21 01:15
@TheFlagCourier  @Emperor-Koala

**Comment by TheFlagCourier** [comment] 2020-08-21 01:42
So, if I'm understanding this correctly, the issue is as follows:
- Local level PVP flags prevent fighting (with a FlagWar Cell event in play.)
- Flag Base Blocks are _NOT_ placeable In Towns preventing FlagWar all together _or_ Multiple Flags can't be placed at once in the same town. (Which is it?)

**Comment by Schnitzengruber** [comment] 2020-08-21 02:11
First bullet is right,
and second bullet- Flag base blocks are NOT placeable in towns, preventing
flag war.

**Comment by TheFlagCourier** [comment] 2020-11-25 08:35
Sorry that it's been so long without follow-up... 

The second bullet is probably related to a player having Towny Admin permissions, either directly through the permission manager, or by a player being OP. FlagWar ignores those players outright, when it comes to initializing. I only say this because I can get FlagWar to fire off just fine on my test server, but it might also be something that someone else fixed.

As for the first bullet, I'll look into it but leave no promises.

If you're still experiencing these problems in 0.96.3.8, or later, let me know please.

**Comment by LlmDl** [comment] 2020-11-25 12:22
The PVP listener redo is happening next, so this will need to be retested.

**Comment by LlmDl** [comment] 2020-12-02 19:23
@TheFlagCourier when I was going over the work on the api/damage_events branch, I can say there's pretty much no way this ticket will still be an issue.

**Comment by TheFlagCourier** [comment] 2020-12-04 05:03
@Schnitzengruber As LlmDl pointed out, this shouldn't be an issue anymore. Since we've received no additional feedback from you since August, I'm closing this ticket. If you still have this issue, chime in and @ me or LlmDl if you think this ticket is still valid and should be reopened.

**Closed by TheFlagCourier** 2020-12-04 05:03 UTC
Labels: Flag War, Need Feedback, bug
