### ISSUE TITLE
TownyChat and DeluxeChat cancel message

### ISSUE THREAD

**Issue by Arkobat** [TownyAdvanced/Towny#3423] opened 2019-10-01 18:23 UTC
### What steps will reproduce the problem?
1. Install TownyChat and DeluxeChat
2. Cancel a message (Via WorldGuard or another plugin)
3. Send a message, that should be canceled.

### What is the expected output?
1. The expected outcome is that no message is sent in the chat

### What is the excat output?
1. The message is sent anyways

### What is your Towny version?
Towny: 0.93.0.0
TownyChat: 0.55

### What is your spigot/craftbukkit version?
Paper-565 (API version 1.13.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/rpcp7uYq

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/P9YBJTqs

3. Your townyperms.yml :
https://pastebin.com/75QDaNqm

4. Your log's error : 
No errors

(optional) If this is to do with chat,
5. Your chatconfig.yml :
https://pastebin.com/dmcAy8Z0

6. Your channels.yml :
https://pastebin.com/FZHuAzsD

7. Your deluxe chat config :
https://pastebin.com/PGyVvUi3

**Comment by LlmDl** [comment] 2019-10-01 19:50
This might be a duplicate of this https://github.com/TownyAdvanced/Towny/issues/3104

Also you should be using 0.94.0.0 on a 1.13 server.

**Comment by LlmDl** [comment] 2019-10-01 19:50
Is the method you're using to cancel the chat in WG that same as the ticket above?

**Comment by Arkobat** [comment] 2019-10-02 13:43
It seems to be a duplicate yes.
I've tried some different ways to cancel the event, including:
- WorldGuard send-chat deny
- EditMobs ingame GUI chat event (Where I set the name with a chat message)
- My own plugin with AsyncChatEvent#setCanceled(true)

**Comment by LlmDl** [comment] 2019-10-02 14:16
Yeah I was looking at it last night and we ignorecancelled=true on it. I'll do some testing to see if there was a reason it was coded that way, it may have something to do with our non-global chat channels.

**Closed** 2019-10-02 14:24 UTC
Labels: duplicate

**Comment by LlmDl** [comment] 2019-10-15 16:41
@Arkobat you can now enjoy this and the rest of the latest Towny features on 1.13 using this special release: https://github.com/TownyAdvanced/Towny/releases/tag/0.95.0.0for1.13.2

**Comment by Arkobat** [comment] 2019-10-20 12:35
@LlmDl So I installed the following from your link.
* Towny 0.95.0.0 for 1.13.2
* TownyChat 0.58
* TownyNameUpdater 4.0

At first, it seemed to work, as I couldn't chat in the region.
However today we had some tests, where users could chat in the region again :I

**Comment by LlmDl** [comment] 2019-10-20 12:38
you're using a WG region to cancel it?

**Comment by Arkobat** [comment] 2019-10-20 12:44
Yes, and I also tried it with my own plugin, just to be sure.

**Comment by LlmDl** [comment] 2019-10-20 12:46
If it was working on your server but now it's not, i'd say something changed on your end.

**Comment by Arkobat** [comment] 2019-10-20 12:52
Do you have a maven dependency for this custom build, or should I just create a mirror myself with the one downloaded?
Can't seem to find this one:
```
        <dependency>
   	        <groupId>com.palmergames.bukkit.towny</groupId>
	        <artifactId>Towny</artifactId>
	        <version>LATEST</version>
	        <scope>provided</scope>
        </dependency>
```
(Thinking of doing some testing to figure my problem out) :)

**Comment by Arkobat** [comment] 2019-10-20 13:16
So, I've tried to fix it.
This change seems to do the trick, at least for now.
Haven't fully tested it, and therefore I'm not sure if my change has more side effects
```
	@EventHandler(priority = EventPriority.LOW)
	public void onPlayerChat(AsyncPlayerChatEvent event) {
		// code
```
```
	@EventHandler
	public void onPlayerChat(AsyncPlayerChatEvent event) {
		if (event.isCancelled()) {
			return;
		}
		// code
```

**Comment by LlmDl** [comment] 2019-10-20 13:19
You did that to TownyChat ?

**Comment by Arkobat** [comment] 2019-10-20 13:20
Yes, forked the lastest version on github and tried

**Comment by LlmDl** [comment] 2019-10-27 20:14
Any side effects come up? Got another user who's said what I did, didn't work for them either.

**Comment by Arkobat** [comment] 2019-10-28 10:02
None found yet :)

**Comment by LlmDl** [comment] 2019-10-28 12:05
Did you test adding the ```		if (event.isCancelled()) {
			return;
		}``` while keeping the priority at low?

**Comment by Arkobat** [comment] 2019-10-28 12:09
As I recall, yes, and the message was sent anyways, until I removed the priority

**Comment by LlmDl** [comment] 2019-10-28 12:10
Thanks, turns out you're not the only one who didn't have it work the way I'd gotten it to work in 0.57

**Comment by Arkobat** [comment] 2019-10-28 12:11
Yeah, I follow both threads xD
