### ISSUE TITLE
Ghost Outposts

### ISSUE THREAD

**Issue by robinkek** [TownyAdvanced/Towny#3844] opened 2020-03-29 19:10 UTC
### What steps will reproduce the problem?
1. Claim Outpost
2. Delete the outpost data? Not sure how it happened or where it is located.
3. Restart Server

### What is the expected output?
1. Outpost no longer exists on the map
2. Outpost is no longer protected
3. You can still teleport to the outpost
4. The numbers on "/t outpost list" are wrong
_outpost list output:_
[screenshot](https://i.imgur.com/xhwk5qI.png)

### What is your Towny version?
Towny 0.96.0.0

### What is your spigot/craftbukkit version?
PaperSpigot #143, MC: 1.15.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.pl/view/9350c223

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.pl/view/996abc5b

3. Your townyperms.yml :
https://pastebin.pl/view/23c6cb32

4. Your log's error : 
none?

**Comment by LlmDl** [comment] 2020-03-29 19:13
If you don't know how the outpost was deleted it is likely the vanishing-townblocks thing. There's currently a pull request for a branch that should solve the issue at its core.

**Comment by robinkek** [comment] 2020-03-31 13:06
Yeah probably. Thanks for letting me know!

**Comment by LlmDl** [comment] 2020-04-04 15:01
I am marking this ticket as a duplicate of [the earliest ticket](https://github.com/TownyAdvanced/Towny/issues/3783) filed for this problem, as no one has said they are still experiencing the issue since 0.96.1.1 was put out.

**Closed by LlmDl** 2020-04-04 15:01 UTC
Labels: bug, duplicate
