### ISSUE TITLE
Suggestion: No timeout for ruined towns

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5036] opened 2021-06-29 06:20 UTC
**Please explain your feature request to the best of your abilities:**

Currently, the maximum amount of time a town can be ruined is 1000 days.
I would like to make this value infinite by setting it to '0'.

**Comment by LlmDl** [comment] 2021-06-29 12:50
Duplicate of https://github.com/TownyAdvanced/Towny/issues/4970

The most you get is a year. It was not made to be an indefinite ruin.

**Closed by LlmDl** 2021-06-29 12:50 UTC
Labels: enhancement

**Comment by MilesBHuff** [comment] 2021-06-29 14:25
Sorry;  I must have forgotten to remove the open-only filter when I searched to make sure I wasn't making a duplicate.

Made to be or not, using things in ways the developers never imagined is an important part of emergent play.  In any case, I've left a comment in the linked issue.
