### ISSUE TITLE
[Bug] Frames and paintings are not removed on unclaim.

### ISSUE THREAD

**Issue by AIphaDragon** [TownyAdvanced/Towny#2951] opened 2018-06-01 23:22 UTC
Hello. Faced a small problem. Frames and paintings are not regenerated, after the destruction of the town. Thanks in advance for your help.

Video: https://youtu.be/nC_ceHJg7js

### What is your Towny version?
0.92.12

### What is your spigot/craftbukkit version?
Spigot 1.11.2 - 1.12.2

### Please use Pastebin.com to link the following files:
1. Full server startup from the logs\latest.log : https://pastebin.com/dPzEH1Zq
2. Towny config.yml : https://pastebin.com/KbgkNiRg

**Comment by LlmDl** [comment] 2018-06-03 17:02
I have tested and confirmed this is happening. I'll have to get it to handle those entities. Probably need to test/add EnderCrystals, ArmorStands to that list and any other blocks which are actually entities.

**Comment by MartenM** [comment] 2018-06-07 20:55
Would a 3x3 check round the block (or only the faces) be enough to solve this problem?
Otherwise I could possibly create a PR for this.

**Comment by LlmDl** [comment] 2018-06-07 21:31
There's two really inefficient ways to do this that i know of:
- check a 3x3 area for each block we're looping through for an entity.
- check the whole world's entities to see if there's one in the plot regenerating.

I'm going to see if there's a way to get all entities in a chunk/space. Hopefully that's the case.

**Comment by LlmDl** [comment] 2018-07-14 17:51
So I figured out that this whole nonsense is actually caused by Towny, in a fix to a pretty obscure but semi-serious bug. I can undo the previous bugfix but there's no way to then re-fix that bug until Spigot fixes/updates their code. I'd elaborate more but don't want the previous bug to become common knowledge.

**Comment by LlmDl** [comment] 2018-07-14 17:56
Fixed as of 0.92.0.13

**Closed by LlmDl** 2018-07-14 17:56 UTC
Labels: bug
